GET http://localhost:3001

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/people

###
POST http://localhost:3001/api/people
Content-Type: application/json

{
    "name": "Carlos Hubert",
    "number": "+55 19 987654321"
}

###
GET http://localhost:3001/api/people/5

###
DELETE http://localhost:3001/api/people/5
